### ISSUE TITLE
Depends on python-pycryptodomex instead of python-pycryptodome

### ISSUE THREAD

**Issue by ZHOUYue67** [ros-noetic-arch/ros-noetic-rosbag#1]
See:  https://pycryptodome.readthedocs.io/en/latest/src/installation.html

PyCryptodome has two forms:
1. named `Crypto` as a drop-in replacement for the old PyCrypto library (Arch package: `python-pycryptodome`)
2. named `Cryptodome` which is independent and can be coexist with PyCrypto (Arch package: `python-pycryptodomex`)

Source code of ros-noetic-rosbag use the latter form:
```python
from Cryptodome.Cipher import AES
```

So we should depend on `python-pycryptodomex` instead of `python-crypto` or `python-pycryptodome`.

If for some reasons we must depend on `python-crypto`, then we have to patch the source, changing`from Cryptodome.Cipher import AES` into `from Crypto.Cipher import AES` for the package to work.

**Comment by acxz** [comment]
Nice to see you again @MikeChou !
Ah I see, feel free to make a PR!

**Comment by acxz** [comment]
Also considering this do you think this requires a change to upstream deps? If so could you post a PR there before we merge it in here? I would like to keep as close to upstream as possible including contributing back any fixes we encounter.

https://github.com/ros/ros_comm/blob/noetic-devel/tools/rosbag/package.xml#L45

**Comment by acxz** [comment]
Just experienced this as well, lets get this fixed ASAP. I'll push a commit out if I don't hear from you within the day, since this is a bit critical.

**Comment by ZHOUYue67** [comment]
Sorry for not doing a PR. A little inconvenient for me right now.

I don't think we should change the upstream. I think they are targeting Ubuntu. And `python3-pycryptodome` in Ubuntu is `python-pycryptodomex` in Arch. Actually your RP in upstream failed their CI, because Ubuntu does not have a package named `python-pycryptodomex`.

I am not familiar with the standard practice to deal with package name differences. If there isn't a mechanism for this, maybe we just patch it in this repo for short terms, and then come up with something for this kind of issues later.

**Comment by acxz** [comment]
Ah thx for explaining that, was wondering why my PR failed haha.

**Comment by acxz** [comment]
Yeah let's just patch it for right now and if other problems show up we will handle it from there.
Just pushed out the fix, thx for reporting!

e75bc83
