### ISSUE TITLE
Build failed: No rule to make target '/usr/lib/libboost_regex.so.1.79.0'

### ISSUE THREAD

**Issue by petronny** [ros-noetic-arch/ros-noetic-rosbag#3]
```
-- Build files have been written to: /build/ros-noetic-rosbag/src/build
make[2]: *** No rule to make target '/usr/lib/libboost_chrono.so.1.79.0', needed by 'devel/lib/rosbag/encrypt'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 10%] Building CXX object CMakeFiles/rosbag.dir/src/player.cpp.o
[ 20%] Building CXX object CMakeFiles/encrypt.dir/src/encrypt.cpp.o
```
https://github.com/arch4edu/cactus/actions/runs/3212783525/jobs/5252003277

It's similar to https://github.com/ros-noetic-arch/ros-noetic-cv-bridge/issues/1 . But I have already rebuilt those packages which directly depend on boost.

**Comment by acxz** [comment]
Sadly, the only current hack that we have for this is to rebuild all ros-noetic-* packages when boost or another core dep gets updated.

If possible, I'd recommend you to do this for arch4edu. Sorry about the inconvenience.

A more proper way to resolve this would be to add boost as a dep to any package which can throw this error. This however requires parsing through all the ros packages and rewriting their dependencies properly, which is something that I don't really have the time for right now. Also with ROS 2 becoming the de facto ROS, I'm in general spending less time on this project, besides just trying to keep it running.

**Comment by petronny** [comment]
I'm trying to find all packages that linked to boost.

Current effort is like
```sh
( for i in $(find /opt/ros -name '*.so')
do
  [ $(ldd $i | grep -c  -P 'boost.*not found') -gt 0 ] && pacman -F $i
done ) | sort | uniq
```

And it does find new packages to rebuild. I'm not sure it solves the problem but it worths a try.

**Comment by petronny** [comment]
Oh, and it does. https://github.com/arch4edu/arch4edu/commit/3b2d98c907392ba649142c8c3ac310321239cc6f

**Comment by petronny** [comment]
Emm, now the error goes to ros-noetic-controller-{manager,diagnostic-updater,tf2-ros}.
Need a new round of digging.

**Comment by petronny** [comment]
`ldd` everything under `/opt/ros` shows more packages to rebuild.
This time there are only 4 packages still failing. We are almost there.

**Comment by petronny** [comment]
> there are only 4 packages still failing.

These 4 packages are finally solved today.

3 of them are rebuilt successfully just after a day.
But `ros-noetic-pcl-ros` still tried to find boost 1.79 while no package in arch4edu is linked to boost 1.79 anymore. `grep 'libboost_system.so.1.79.0'` under `/opt/ros` shows `ros-noetic-pcl-conversions` has hard-coded boost libraries in `pcl_conversionsConfig.cmake` and `pcl_conversions.pc`. After rebuilding `ros-noetic-pcl-conversions`, `ros-noetic-pcl-ros` is successfully built.

I think all ros-noetic packages are fine now.

BTW, I'm thinking about providing ros/ros2 packages for aarch64 in arch4edu. Is it necessary?

**Comment by acxz** [comment]
Nice, thanks for hunting this done @petronny
It has been really useful.

> I'm thinking about providing ros/ros2 packages for aarch64 in arch4edu. Is it necessary?

So far, no one has requested aarch64 packages for ROS. The only realistic use case I would see is if someone is using Archlinux32 on a raspberry pi. I would say don't worry about it now, until we have someone specifically make a request for it. Although I woul imagine that aarch64 would probably work.
